/**
 * 配置的注册信息 数据持久化
 *
 * sobird<i@sobird.me> at 2024/04/23 15:50:54 created.
 */

import fs from 'fs';

const Warning = 'This file is automatically generated by runner. Do not edit it manually unless you know what you are doing. Removing this file will cause runner to re-register as a new runner.';

export class Registration {
  public WARNING: string = Warning;

  constructor(
    public id: string,
    public uuid: string,
    public name: string,
    public token: string,
    public address: string,
    public labels: string[],
  ) {}

  save(file: string) {
    // Convert the object to a JSON string with 2-space indentation
    const data = JSON.stringify(this, null, 2);
    fs.writeFileSync(file, data, 'utf8');
  }

  static Load(file: string) {
    if (!fs.existsSync(file)) {
      return;
    }
    const {
      id, uuid, name, token, address, labels,
    } = JSON.parse(fs.readFileSync(file, 'utf8'));
    return new Registration(id, uuid, name, token, address, labels);
  }
}
