/**
 * 配置的注册信息 数据持久化
 *
 * sobird<i@sobird.me> at 2024/04/23 15:50:54 created.
 */

import fs from 'fs';

import { readJsonSync } from '@/utils';

const WARNING = 'This file is automatically generated by runner. Do not edit it manually unless you know what you are doing. Removing this file will cause runner to re-register as a new runner.';

export class Registration {
  public id: string;

  public uuid: string;

  public name: string;

  public token: string;

  public address: string;

  public labels: string[];

  public WARNING: string = WARNING;

  #file: string = '.runner';

  constructor(registration: Registration, file: string) {
    this.#file = file;

    this.id = registration.id;
    this.uuid = registration.uuid;
    this.name = registration.name;
    this.token = registration.token;
    this.address = registration.address;
    this.labels = registration.labels ?? [];
  }

  get file() {
    return this.#file;
  }

  set file(file: string) {
    this.#file = file;
  }

  save() {
    // Convert the object to a JSON string with 2-space indentation
    fs.writeFileSync(this.#file, JSON.stringify(this, null, 2), 'utf8');
  }

  static Load(file: string) {
    const register = readJsonSync(file);
    return new Registration(register, file);
  }
}
