name: Job for Development
run-name: Job for Development By ${{ github.actor }}
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  job-for-development:
    runs-on: ubuntu-latest

    # services:
    #   nginx:
    #     image: nginx
    #     # Map port 8080 on the Docker host to port 80 on the nginx container
    #     ports:
    #       - 8080:80
    #   redis:
    #     image: redis
    #     # Map TCP port 6379 on Docker host to a random free port on the Redis container
    #     ports:
    #       - 6379/tcp

    steps:
      # - name: Print env
      #   # if: ${{ ddd }}
      #   # shell: bash
      #   # working-directory: '.'
      #   # env:
      #   #   FIRST_NAME: Mona
      #   #   LAST_NAME: Octocat
      #   run: cat "$GITHUB_STATE"

      - name: Checkout Step
        uses: actions/checkout@v4
        # with:
        #   token: "f00777300d6fee37b9f913f4f7f0ba9fba07e1d3"
        #   ref: 'refs/heads/main'
        #   repository: 'sobird/actions-test'
        #   github-server-url: 'http://192.168.50.100:3000'

      # - name: Test Actions 1
      #   if: runner.os == 'linux1'
      #   uses: sobird/actions-test@1cb40cff047a5892397986ed61dfbcfc4020fe74
        
      # - name: Hello World Javascript Action Step
      #   id: hello_world_javascript_action
      #   uses: ./.github/actions/hello-world-javascript-action
      #   with:
      #     who-to-greet: 'hello world javascript action step'

      # - name: Test Actions 2
      #   uses: sobird/actions-test@1cb40cff047a5892397986ed61dfbcfc4020fe74

      # - name: Docker Hub Action
      #   uses: docker://alpine:3.8
      #   with:
      #     entrypoint: echo
      #     args: "The ${{ github.event_name }} event triggered this step. runner os: ${{runner.os}}"

      # - name: Hello world Docker File Step
      #   id: hello_world_docker_file
      #   uses: ./.github/actions/hello-world-docker-file
      #   with:
      #     who-to-greet: 'docker file'
          # entrypoint: sh -c 'echo $GITHUB_SHA'
          # args: docker123 file

      # - name: Hello world Docker Action Step
      #   id: hello_world_docker_action
      #   uses: ./.github/actions/hello-world-docker-action
      #   with:
      #     who-to-greet: 'docker action step'
      
      # - name: Get the Docker output time
      #   run: echo "The time was ${{ steps.hello_world_docker_file.outputs.time }}"

      # - name: Hello world Docker Hub Action Step
      #   id: hello_world_docker_hub_action
      #   uses: ./.github/actions/hello-world-docker-hub-action
      #   with:
      #     who-to-greet: 'docker hub action step'

      # - name: Get the Docker Hub output time
      #   run: echo "The time was ${{ steps.hello_world_docker_hub_action.outputs.time }}"
      # - run: apt-get -qq update && apt-get -yqq install --no-install-recommends curl net-tools
      # - run: netstat -tlpen
      # - run: curl -v http://nginx

      - name: Hello World Composite Action
        id: hello_world_composite_hub_action
        uses: ./.github/actions/hello-world-composite-action
        with:
          who-to-greet: 'composite action step'

      # - name: Hello World Composite Action Remote
      #   id: hello_world_composite_hub_action_remote
      #   uses: sobird/actions-test@5af1e59445fd3a2d02f668c20f925aaa0ef4aa94
      #   with:
      #     who-to-greet: 'composite action step'