name: single-step-test
run-name: single-step-test-${{ github.actor }}
on:
  push:

jobs:
  single-step-test:
    runs-on: ubuntu-latest

    services:
      nginx:
        image: nginx
        # Map port 8080 on the Docker host to port 80 on the nginx container
        ports:
          - 8080:80
      redis:
        image: redis
        # Map TCP port 6379 on Docker host to a random free port on the Redis container
        ports:
          - 6379/tcp

    steps:
      - name: print env
        # shell: bash
        # working-directory: '.'
        env:
          FIRST_NAME: Mona
          LAST_NAME: Octocat
        run: env
      - name: ls
        run: ls -l