name: Reusable Workflow Test
run-name: reusable workflows in the same repository ${{ github.event }}
on: 
  push:
    branches:
      - master

permissions:
  contents: read

jobs:
  test-job-uses:
    strategy:
      matrix:
        os: ['ubuntu-latest']
        node: [20]
      fail-fast: false
    # Cannot define both `uses` and `steps` at the same time for the following jobs: job-uses
    uses: ./.github/workflows/test-reusable-workflow.yml