// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file ping/v1/services.proto (package ping.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { PingRequest, PingResponse } from "./messages_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service ping.v1.PingService
 */
export const PingService = {
  typeName: "ping.v1.PingService",
  methods: {
    /**
     * @generated from rpc ping.v1.PingService.Ping
     */
    ping: {
      name: "Ping",
      I: PingRequest,
      O: PingResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

